---
title: "Jhamon Results"
format:
  docx:
    toc: true
    number-sections: true
    highlight-style: github

---

```{python}
# | echo: false
import json
from jhamon_training.pathutils import RESULTS_TRAINING_PATH

# Load the statistics from the JSON file
stats_path = RESULTS_TRAINING_PATH / "training_stats.json"
with open(stats_path) as f:
    stats = json.load(f)

# Round specific ANOVA values to 1 decimal point
stats["anova_peak_torque_group_f"] = round(stats["anova_peak_torque_group_f"], 1)
stats["anova_knee_ROM_group_f"] = round(stats["anova_knee_ROM_group_f"], 1)
```


The total number of repetitions analysed was `{python} stats["total_reps"]`, with `{python} stats["nh_reps"]` repetitions from the NH group (`{python} stats["nh_percentage"]`% of the total `{python} stats["prescribed_total_nh"]` prescribed repetitions in the training program) and `{python} stats["ik_reps"]` repetitions from the IK group. On average, participants in the IK group performed `{python} stats["rep_diff"]` ± `{python} stats["rep_diff_sd"]` repetitions `{python} stats["rep_diff_sign"]` per set than the NH group. This difference increased from `{python} stats["tr1_avg_diff"]` ± `{python} stats["tr1_avg_diff_sd"]` repetitions in the first training session to `{python} stats["tr15_avg_diff"]` ± `{python} stats["tr15_avg_diff_sd"]` at the fifteenth IK training session (Figure 3A).

The amount of work per repetition was greater in the NH group compared to the IK group (`{python} stats["nh_work_mean"]` ± `{python} stats["nh_work_sd"]` J vs `{python} stats["ik_work_mean"]` ± `{python} stats["ik_work_sd"]` J; *p* < 0.001; Figure 3B). Nevertheless, the total amount of work per set was similar between the two groups (Figure 3C). 


Mean and peak torque, knee ROM, the angle at peak torque, and knee velocity values across training sessions are shown in Figure 4. Higher peak torque values were observed in the NH group compared to the IK group (`{python} stats["anova_peak_torque_group_mean"]["NH"]` ± `{python} stats["anova_peak_torque_group_sd"]["NH"]` Nm vs `{python} stats["anova_peak_torque_group_mean"]["IK"]` ± `{python} stats["anova_peak_torque_group_sd"]["IK"]` Nm; *F* = `{python} stats["anova_peak_torque_group_f"]`, *p* = `{python} stats["anova_peak_torque_group_p"]`). No main effect of training group was observed for mean torque (*F* = `{python} stats["anova_mean_torque_group_f"]`, *p* = `{python} stats["anova_mean_torque_group_p"]`) or knee ROM (*F* = `{python} stats["anova_knee_ROM_group_f"]`, *p* = `{python} stats["anova_knee_ROM_group_p"]`). However, a significant main effect of group was observed for knee angle at peak torque (`{python} stats["anova_angle_at_peak_torque_group_mean"]["NH"]` ± `{python} stats["anova_angle_at_peak_torque_group_sd"]["NH"]`° vs `{python} stats["anova_angle_at_peak_torque_group_mean"]["IK"]` ± `{python} stats["anova_angle_at_peak_torque_group_sd"]["IK"]`°; *F* = `{python} stats["anova_angle_at_peak_torque_group_f"]`, *p* < 0.001, $\eta^2$ = `{python} stats["anova_angle_at_peak_torque_group_eta"]`). A significant main effect of time was observed for mean torque (*F* = `{python} stats["anova_mean_torque_time_f"]`, *p* < 0.001, $\eta^2$ = `{python} stats["anova_mean_torque_time_eta"]`), peak torque (*F* = `{python} stats["anova_peak_torque_time_f"]`, *p* < 0.001, $\eta^2$ = `{python} stats["anova_peak_torque_time_eta"]`), knee ROM (*F* = `{python} stats["anova_knee_ROM_time_f"]`, *p* < 0.001, $\eta^2$ = `{python} stats["anova_knee_ROM_time_eta"]`), and angle at peak torque (*F* = `{python} stats["anova_angle_at_peak_torque_time_f"]`, *p* < 0.001, $\eta^2$ = `{python} stats["anova_angle_at_peak_torque_time_eta"]`).

A significant main effect of group was also observed for mean knee velocity (`{python} stats["anova_knee_v_mean_group_mean"]["NH"]` ± `{python} stats["anova_knee_v_mean_group_sd"]["NH"]`°/s vs `{python} stats["anova_knee_v_mean_group_mean"]["IK"]` ± `{python} stats["anova_knee_v_mean_group_sd"]["IK"]`°/s; *F* = `{python} stats["anova_knee_v_mean_group_f"]`, *p* = `{python} stats["anova_knee_v_mean_group_p"]`, $\eta^2$ = `{python} stats["anova_knee_v_mean_group_eta"]`), with higher values in the NH group. A significant main effect of time was also observed for mean knee velocity (*F* = `{python} stats["anova_knee_v_mean_time_f"]`, *p* < 0.001, $\eta^2$ = `{python} stats["anova_knee_v_mean_time_eta"]`).

SPM analyses on the normalized torque and velocity patterns are shown in Figure 5. In the beginning of the contraction, greater knee joint torque values were observed in the IK group compared to the NH group (0-37%). Greater torque calues were observed in the NH group in the last half of the movement (supra threshold cluster from 48% to 100%). Different patterns were also observed in the knee velocity data, with greater knee angular velocity values in the IK group during the three first quarters of the movement (0.9-73%, CT = 2.729) and the opposite pattern in the last quarter of the movement, with greater knee angular velocity values in the NH group (Figure 5C and 5D).

Progression of the normalized torque and velocity patterns across training sessions is shown in Figure 6.

Bland-Altman plots are shown in Figure 7.

























